### ISSUE TITLE
unk replacement with corresponding words in source input in the output sentences when using --predict_from_input

### ISSUE THREAD

**Issue by liperrino** [lukemelas/machine-translation#1]
please i would like to replace the unk in the output sentences with the corresponding words in the source sentence when using the option: --predict_from_input. Meaning going from german to english, if a word was seen as unk in the provided sentence it should appear exactly in the output sentence at the good position.

**Comment by lukemelas** [comment]
Hello,

Thanks for your interest in the repo. 

If you do not want <UNK> in your predictions, you can manually block the network from producing the <UNK> character using the remove_tokens argument in model.predict_k. For example, you can do exactly what is done on line 21 before line 43 in training/predict.py

**Comment by liperrino** [comment]
Thanks a lot for the proposition. But to be sure we are talking about the same thing, let us considerate that we are making a traduction from English to French. Under is a better explanation of what i want.

INPUT SENTENCE                           : **i am going to school tomorrow with my teacher**.
INPUT USE BY predict_from_input  : **i am going to school <unk> with my <unk>**
OUTPUT  RESULT                           :  je vais à l'école <unk> avec mon <unk>
WHAT I WANT AS RESULT             :  **je vais à l'école tomorrow avec mon teacher**

**Comment by liperrino** [comment]
> Thanks a lot for the proposition. But to be sure we are talking about the same thing, let us considerate that we are making a traduction from English to French. Under is a better explanation of what i want.
> 
> INPUT SENTENCE : **i am going to school tomorrow with my teacher**.
> INPUT USE BY predict_from_input : **i am going to school with my **
> OUTPUT RESULT : je vais à l'école avec mon 
> WHAT I WANT AS RESULT : **je vais à l'école tomorrow avec mon teacher**


INPUT SENTENCE                            : i am going to school tomorrow with my teacher.
INPUT USE BY predict_from_input   : i am going to school _**unk**_ with my _**unk**_
RESULT                                            : je vais à l'école _**unk**_ avec mon _**unk**_

WHAT I WANT AS RESULT               : je vais à l'école tomorrow avec mon teacher

**Comment by liperrino** [comment]
I have train the model using the default parameters but when doing the prediction like in your post:
, i obtain a different result.

German: Ihre <unk> erwies sich als komplizierter als gedacht .
1: Her <unk> were willing to think more than more than exciting .
2: Her <unk> turned to themselves more complicated than exciting .
3: Her <unk> were willing to think more than more than anticipated .
4: Her <unk> were willing to think more than harder than thought .
5: Her <unk> were willing to think more than more than complex than most .
Finished in 0.3209352493286133

**Comment by liperrino** [comment]
Is something wrong with the model: I used this input: Wir bringen Kinder zur welt . 
I obtained this results:

German: Wir bringen Kinder zur <unk>
1: We bring kids to children to <unk> children to the <unk> children <unk> children to introduce children to children imaging . We bring children to pet <unk> .
2: We bring kids to children to <unk> children to the <unk> children <unk> children to introduce children to children imaging . We gather kids to <unk> children to <unk> children
3: We bring kids to children to <unk> children to the <unk> children <unk> children to introduce children to children imaging . We gather children to <unk> children to <unk> children
4: We bring kids to children to <unk> children to the <unk> children <unk> children to introduce children to children imaging . We bring children to pet <unk> ,
5: We bring kids to children to <unk> children to the <unk> children <unk> children to introduce children to children imaging . We bring children to pet <unk> . We bring

**Comment by liperrino** [comment]
I have try to use GRU instead of LSTM and i am having errors. Please try to check it for me.

**Comment by liperrino** [comment]
Happy New Year. Please how can i used GRU instead of LSTM in your code?

**Comment by lukemelas** [comment]
Hello,

Apologies for the late reply. I am currently traveling, but I will
absolutely respond to you about using GRUs when I return to school.

Best,
Luke

**Comment by liperrino** [comment]
Thanks a lot

**Comment by lukemelas** [comment]
Just got back to school! 

To switch from LSTM to GRU, try the following: 
- Change line 17 in `models/Decoder.py `and line 18 in `models/Encoder.py ` from `LSTM` to `GRU`
- Change lines 27-30 in `models/Encoder.py `such that `h0 `is a single tensor (i.e. `init`) rather than a tuple of tensors (i.e. `(init, init.clone())`). 

Let me know how it works for you!

**Comment by liperrino** [comment]
Thank you very much. I will definetly try it and give you feedback.

**Comment by liperrino** [comment]
Please like i tall you before i would like to change your code to get something like this:

INPUT SENTENCE : i am going to school tomorrow with my teacher.
INPUT USE BY predict_from_input : i am going to school **unk** with my **unk**
RESULT : je vais à l'école **unk** avec mon **unk**

WHAT I WANT AS RESULT : je vais à l'école **tomorrow** avec mon **teacher**


Please how can i do this?

**Comment by liperrino** [comment]
Hello. I have change it like you have said for GRU. But i get nan concerning loss after epoch 1. Here is the output:

Loaded embedding vectors from np files
Weight tying!
Validation complete. BLEU: 0.000
New best: 0.000
Validation time: 115.180
PPL: 1.000

Epoch [1/50]     Batch [10/1861]         Loss: 7.769

Epoch [1/50]     Batch [1010/1861]       Loss: 4.505


Epoch [1/50] complete. Loss: nan
Training time: 47292.040
Validation complete. BLEU: 0.000
Validation time: 84.113
PPL: 1.000
Epoch [2/50]     Batch [10/1861]         Loss: nan
Epoch [2/50]     Batch [1010/1861]       Loss: nan
Epoch [2/50] complete. Loss: nan
Training time: 6695.366
Validation complete. BLEU: 0.000
Validation time: 92.769
PPL: 1.000
Epoch [3/50]     Batch [10/1861]         Loss: nan
Epoch [3/50]     Batch [1010/1861]       Loss: nan
Epoch [3/50] complete. Loss: nan
Training time: 5903.140
Validation complete. BLEU: 0.000
Validation time: 89.201
PPL: 1.000
Epoch [4/50]     Batch [10/1861]         Loss: nan

**Comment by liperrino** [comment]
According to the results of your work done, i noticed that when phrase is entered in a source language (ex : German), the output results (phrases) is processed in a target language (ex : English), my question goes this way ; « Is the processed result based on translation only ? prediction only ? Or translation while taking into consideration some prediction ??

**Comment by liperrino** [comment]
I have so many question concerning your work. But i am afraid to disturb you. I don't know if i should expose them to you or not.

**Comment by liperrino** [comment]
I would like to try:
- teacher forcing
- label smoothing
- attention
- transformer

Please guide me to do this.

**Comment by liperrino** [comment]
I have made a mistake you have already do attention

**Comment by lukemelas** [comment]
Hello,

Yes, attention is already implemented :)

I must say, however, this repository is meant to be more of a simple
example of sequence-to-sequence machine translation than a platform for
implementing state-of-the-art models. If you are looking to explore all the
super interesting ideas you mentioned above, I highly recommend checking
out either OpenNMT or fairseq:

https://github.com/OpenNMT/OpenNMT-py
https://github.com/pytorch/fairseq

These are both actively maintained, highly flexible frameworks for
conducting cutting-edge research :)

**Comment by liperrino** [comment]
Thanks a lot

**Comment by liperrino** [comment]
Hi. Please i would like to add some features i have read on beam search. Like coverage penalty and length normalization. But i don't know where to start. Can you help please?

**Comment by liperrino** [comment]
Hi. Please i still have some problems with the code. I got nan for the lost when training it.
Loaded data. |TRG| = 11560. Time: 65.22.
Loaded embedding vectors from np files
Weight tying!
/home/vivien/Bureau/NMT/Look/Machine-Translation-master/models/Seq2seq.py:90: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  last_word_input = Variable(torch.LongTensor([last_word]), volatile=True).view(1,1)
Validation complete. BLEU: 0.000
New best: 0.000
Validation time: 75.053
PPL: 1.000
Epoch [1/25]	 Batch [10/1861]	 Loss: 7.669
Epoch [1/25]	 Batch [1010/1861]	 Loss: nan

**Comment by deHasara** [comment]
`This is a test of our preprocessing function. It took 46.7 seconds to load the data. Our German vocab has size 13354 and our English vocab has size 11560. Our training data has 7443 batches, each with 16 sentences, and our validation data has 570 batches.
Validating Epoch [0/50]	 Average loss: 9.379	 Perplexity: 11833.884
Epoch [1/50]	 Batch [10/7443]	 Loss: 8.345
Epoch [1/50]	 Batch [1010/7443]	 Loss: 4.692
Epoch [1/50]	 Batch [2010/7443]	 Loss: 4.192
Traceback (most recent call last):
  File "/home/hasara/python code/benchmark- IWSLT data/test.py", line 334, in <module>
    train(train_iter, val_iter, model, criterion, optimizer, 50)
  File "/home/hasara/python code/benchmark- IWSLT data/test.py", line 255, in train
    scores = model(src, tgt)
  File "/home/hasara/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hasara/python code/benchmark- IWSLT data/test.py", line 159, in forward
    out_e, final_e = self.encoder(src)
  File "/home/hasara/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hasara/python code/benchmark- IWSLT data/test.py", line 75, in forward
    x = self.dropout(self.embedding(x)) # embedding
  File "/home/hasara/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hasara/.local/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/hasara/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1724, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self`

How can I resolve this error?

**Comment by AungZinPyae** [comment]
> Please like i tall you before i would like to change your code to get something like this:
> 
> INPUT SENTENCE : i am going to school tomorrow with my teacher.
> INPUT USE BY predict_from_input : i am going to school **unk** with my **unk**
> RESULT : je vais à l'école **unk** avec mon **unk**
> 
> WHAT I WANT AS RESULT : je vais à l'école **tomorrow** avec mon **teacher**
> 
> Please how can i do this?

Have you found the solution for that?
